Platzigram/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.urls import re_path

#
from Platzigram import views as local_views
from posts import views as posts_views
from users import views as users_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello-world/', local_views.hello_world, name="hello_world"),
    path('sorted/', local_views.sort_integers, name="sorted"),
    path('hi/<str:name>/<int:age>/', local_views.say_hi, name="hi"),
    
    path('', local_views.home, name="home"),

    #Posts
    path('posts/', include(('posts.urls', 'posts'), namespace="posts")),

    # Users
    path('users/', include(('users.urls', 'users'), namespace="users")),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

# Posts urls
from posts import views as posts_views
# API Posts urls
from posts import viewsApi

#API REST
from rest_framework import routers
router = routers.DefaultRouter()


#API
# En el router vamos añadiendo los endpoints a los viewsets
router.register('list_post', viewsApi.PostViewSet)


urlpatterns = [
    #Posts
    # path(
    #     route='',
    #     view=posts_views.list_posts,
    #     name="feed"
    # ),
    path(
        route='',
        view=posts_views.PostsFeedView.as_view(),
        name='feed'
    ),
    path('demo/', posts_views.list_posts2, name="feed2"),
    path('new/', posts_views.create_posts, name="create_posts"),
    path('ej1/', posts_views.list_posts_ej1, name="post_ej"),

    path('api/', include(router.urls)),

]

users/urls.py
from django.urls import path, include
# Users urls
from users import views as users_views
from django.views.generic import TemplateView

# Django rest framework
from rest_framework import routers

# Api
from users import viewsApi

router = routers.DefaultRouter()
router.register('list_profiles', viewsApi.ProfileViewSet)

app_name = 'users'
urlpatterns = [

    # Posts
    path(
        route='<str:username>/',
        # view=TemplateView.as_view(template_name='users/detail.html'),
        view=users_views.UserDetailView.as_view(),
        name='detail'
    ),

    # Management
    path('login',users_views.login_view, name="login" ),
    path('logout',users_views.logout_view, name="logout" ),
    path('signup/view',users_views.signup_view, name="signup_view" ),
    path('signup',users_views.signup, name="signup" ),

    #Middlewares
    path('me/profile', users_views.update_profile, name="update_profile" ),

    # API
    path('api/', include(router.urls)),
]

users/models.py
# Djando
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    ''' Profile model
        proxy model that extends the base data with other information
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to="users/picture",
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(
        min_length=4,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Username',
                'required': True
            }
        ))

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'********',
                'required': True
                }
            ),
        )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'********',
                'required': True
                }
        ),
    )

    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'First Name',
                'required': True
            }
        )
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Last Name',
                'required': True
            }
        )
    )

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(
            attrs={
                'class':'form-control',
                'placeholder':'example@platzigram.com',
                'required': True
            }
        ),
    )

    # Validando Usuario existe
    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists() #regresa un booleano
        if username_taken:
            raise forms.ValidationError('Username is already in use.') #lanzamos excepción
        return username

    # Validando password
    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation') # descartar dato que no se almacenará

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

class ProfileForm(forms.Form):
    """Profile form."""

    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

users/views.py
# User Views

#Django
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

# Exception
from django.db.utils import IntegrityError

# Models
from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post

#form
from users.forms import ProfileForm, SignupForm

# Create your views here.
def login_view(request):
    """ Login view"""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # Prueba en local
        # print(username, ':', password)
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('posts:feed') # urls.py
        else:
            return render(request, 'users/login.html', {'error': 'Invalid username and password'})

    # Si el usuario ya está autenticado
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('posts:feed')

    return render(request, 'users/login.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')

# Signup por medio de vistas
def signup_view(request):
    """ Signup view """
    #Debugger
    # import pdb;pdb.set_trace()
    if request.method == 'POST':
        username = request.POST['username']
        passwd = request.POST['passwd']
        passwd_confirmation = request.POST['passwd_confirmation']

        if passwd != passwd_confirmation:
            return render(request, 'users/signup_view.html', {'error': 'Password confirmation does not match'})

        try:
            user = User.objects.create_user(username=username, password=passwd)
        except IntegrityError:
            return render(request, 'users/signup_view.html', {'error': 'Username is already in user'})

        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user.save()

        profile = Profile(user=user)
        profile.save()
        return redirect('users:login')

    return render(request, 'users/signup_view.html')

# Signup por medio de form
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = SignupForm()

    return render(
        request=request,
        template_name='users/signup.html',
        context={'form': form}
    )

def update_profile(request):
    """Update a users profile view """
    profile = request.user.profile
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()

            print(form.cleaned_data)

            url = reverse('users:detail', kwargs={'username': request.user.username})
            return redirect(url)
    else:
        form = ProfileForm()

    return render(
        request=request,
        template_name='users/update_profile.html',
        context={
            'profile':profile,
            'user':request.user,
            'form':form
        }
    )

class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4"
                        style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="150px"
                />
            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update_profile" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign in</title>
{% endblock%}

{% block container %}

    {% if error %}
        <p class="alert alert-danger" >{{ error }}</p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>
        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>
        <div class="form-group">
            <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
        </div>
    </form>
    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>

{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'user:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/signup_view.html
{% extends "users/base.html" %}

{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="passwd" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password confirmation" name="passwd_confirmation" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="text" placeholder="First name" name="first_name" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Last name" name="last_name" required="true" />
        </div>

        <div class="form-group">
            <input class="form-control" type="email" placeholder="Email address" name="email" required="true" />
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">
    {% if not profile.picture or not profile.biography %}
        <p class="alert alert-warning">
            Registro incompleto: Antes de acceder a la pantalla principal, asegurate de completa tu
            registro con foto de perfil y biografía.
        </p>
    {% endif %}
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">
            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture: </b>{{ error }}
                    </div>
                {% endfor %}

                <hr><br>
                {# Website fields #}
                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="url"
                        name="website"
                        placeholder="Website"
                        value=" {% if form.errors %}
                                    {{ form.website.value }}
                                {% else %}
                                    {{ profile.website }}
                                {% endif%}
                            "
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                                name="biography"
                    >
                        {% if form.errors %}
                            {{ form.biography.value }}
                        {% else %}
                            {{ profile.biography }}
                        {% endif%}
                    </textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value=" {% if form.errors %}
                                    {{ form.phone_number.value }}
                                {% else %}
                                    {{ profile.phone_number }}
                                {% endif%}
                            "
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{error}}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}